### ISSUE TITLE
Doesn't run in the sandbox

### ISSUE THREAD

**Issue by ghartwich** [iamrob-nl/VectorGauge#1]
Hi,
I have this widget running locally and it works great. But when I run it on the sandbox it throws a Build error. Running the Widget checker (under menu tools in the modeler) it says that this widget will not run in a production environment.  

MX6.3.1

**Comment by iamrob-nl** [comment]
Hi, 

This is something new to me...I will look into it. As soon as I have an answer to this, I'll let you know.

**Comment by ghartwich** [comment]
Hi,

This is my trace of deployment\data\temp\dojo\build-report.txt:
(it contains an error:
error(311) Missing dependency.
module: VectorGauge/lib/snap.svg; dependency: eve)

Build started: Mon Apr 04 2016 14:38:11 GMT+0200 (W. Europe Daylight Time)
Build application version: 1.10.2 (00884aa)
Messages:
info(100) Assumed module uses legacy loader API.
    module: VectorGauge/lib/eve
info(107) Package Version:
    package: dijit; version: 1.10.2
    package: dojo; version: 1.10.2
warn(205) Module not tagged as pure AMD yet it contains AMD API applications.
    module: dojox/main
    module: dojox/date/buddhist
    module: dojox/date/hebrew
    module: dojox/date/islamic
    module: dojox/date/persian
    module: dojox/date/posix
    module: dojox/date/relative
    module: dojox/date/timezone
    module: dojox/date/umalqura
    module: dojox/date/buddhist/Date
    module: dojox/date/buddhist/locale
    module: dojox/date/hebrew/Date
    module: dojox/date/hebrew/locale
    module: dojox/date/hebrew/numerals
    module: dojox/date/islamic/Date
    module: dojox/date/islamic/locale
    module: dojox/date/persian/Date
    module: dojox/date/persian/locale
    module: dojox/date/umalqura/Date
    module: dojox/date/umalqura/locale
    module: mxui/dom
    module: mxui/mxui
    module: mxui/html/parser
    module: mxui/lib/ColumnResizer
    module: mxui/lib/form/InlineForm
    module: mxui/lib/form/_FormBase
    module: mxui/mixin/_Stateful
    module: mxui/mixin/_ValidationHelper
    module: mxui/widget/Image
    module: mxui/widget/_Button
    module: mxui/widget/_FormWidget
    module: mxui/widget/_WidgetBase
    module: mendix/lang
    module: mendix/lib/Error
    module: mendix/lib/MxContext
    module: mendix/lib/MxMetaObject
    module: mendix/lib/MxObject
    module: mendix/lib/ObjectValidation
    module: VectorGauge/lib/jquery-1.11.2
    module: VectorGauge/lib/snap.svg
    module: VectorGauge/widget/VectorGauge
    module: widgets/widgets
warn(209) Missing or empty package.json.
    filename: C:/Program Files/Mendix/6.3.1/modeler/tools/grunt/dojox/package.json
    filename: C:/Program Files/Mendix/6.3.1/modeler/tools/grunt/mxui/package.json
    filename: C:/Program Files/Mendix/6.3.1/modeler/tools/grunt/mendix/package.json
    filename: C:/Users/Laptop/Desktop/New folder (4)/VectorGauge-master/test/deployment/web/widgets/VectorGauge/package.json
    filename: C:/Users/Laptop/Desktop/New folder (4)/VectorGauge-master/test/deployment/data/tmp/widgets/package.json
warn(216) dojo/has plugin resource could not be resolved during build-time.
    plugin resource id: dojo-bidi?./_BidiMixin; reference module id: dijit/_WidgetBase
    plugin resource id: dojo-firebug?./_firebug/firebug; reference module id: dojo/main
    plugin resource id: dom-addeventlistener?:./aspect; reference module id: dojo/on
    plugin resource id: host-browser?dom-addeventlistener?:../on:; reference module id: dojo/request/watch
warn(224) A plugin dependency was encountered but there was no build-time plugin resolver.
    module: dijit/Fieldset; plugin: dojo/query
    module: dijit/RadioMenuItem; plugin: dojo/query
    module: dijit/Tree; plugin: dojo/query
    module: dijit/form/_RadioButtonMixin; plugin: dojo/query
    module: dojo/request; plugin: dojo/request/default
    module: dojo/request/node; plugin: dojo/node
    module: dojo/request/node; plugin: dojo/node
    module: dojo/request/node; plugin: dojo/node
    module: dojo/request/node; plugin: dojo/node
    module: dojo/request/registry; plugin: dojo/request/default
error(311) Missing dependency.
    module: VectorGauge/lib/snap.svg; dependency: eve
Layer Contents:
mxui/mxui:
    mxui/mxui
    mxui/widget/_WidgetBase
    mxui/widget/_Button
    mxui/lib/ColumnResizer
    mxui/lib/form/_FormBase
    mxui/lib/form/InlineForm
    mxui/mixin/_Stateful
    mxui/mixin/_ValidationHelper
    mxui/dom
    mxui/html/parser
    mxui/widget/_FormWidget
    mxui/widget/Image
    mendix/lib/MxObject
    mendix/lib/MxMetaObject
    mendix/lib/MxContext
    mendix/lib/ObjectValidation
    mendix/lib/Error
    mendix/lang
    dojo/selector/acme
    dojo/io/iframe
    dojo/request/iframe
    dojo/window
    dijit/focus
    dojo/Stateful
    dijit/a11y
    dijit/main
    dijit/registry
    dijit/_base/focus
    dijit/selection
    dijit/_TemplatedMixin
    dojo/cache
    dojo/text
    dojo/request
    dojo/request/default
    dojo/string
    dijit/_AttachMixin
    dojo/touch
    dijit/_WidgetBase
    dijit/Destroyable
    dijit/Tooltip
    dijit/_base/manager
    dijit/place
    dijit/Viewport
    dijit/_Widget
    dijit/_OnDijitClickMixin
    dijit/a11yclick
    dijit/_FocusMixin
    dojo/uacss
    dijit/hccss
    dojo/hccss
    dijit/BackgroundIframe
    dijit/templates/Tooltip.html
    dijit/_base
    dijit/WidgetSet
    dijit/_base/place
    dijit/_base/popup
    dijit/popup
    dijit/_base/scroll
    dijit/_base/sniff
    dijit/_base/typematic
    dijit/typematic
    dijit/_base/wai
    dijit/_base/window
    dojo/i18n
    dojo/number
    dojo/cldr/nls/number
    dojo/regexp
    dojo/fx
    dojo/fx/Toggler
    dijit/_Container
    dijit/_Contained
    dijit/Calendar
    dojo/date
    dojo/date/locale
    dojo/cldr/supplemental
    dojo/cldr/nls/gregorian
    dijit/CalendarLite
    dojo/date/stamp
    dijit/templates/Calendar.html
    dijit/_CssStateMixin
    dijit/form/DropDownButton
    dijit/form/Button
    dijit/form/_FormWidget
    dijit/form/_FormWidgetMixin
    dijit/form/_ButtonMixin
    dijit/form/templates/Button.html
    dijit/_HasDropDown
    dijit/form/templates/DropDownButton.html
    dijit/layout/BorderContainer
    dojo/cookie
    dijit/layout/LayoutContainer
    dijit/layout/_LayoutWidget
    dijit/layout/utils
    dijit/layout/ContentPane
    dijit/layout/_ContentPaneResizeMixin
    dojo/html
    dojo/parser
    dojo/_base/url
    dojo/promise/all
    dijit/nls/loading
    dojox/date/buddhist
    dojox/main
    dojox/date/buddhist/Date
    dojox/date/buddhist/locale
    dojo/cldr/nls/buddhist
    dojo/hash
    dijit/_Templated
    dijit/_WidgetsInTemplateMixin
    dijit/form/_FormValueWidget
    dijit/form/_FormValueMixin
    dijit/form/ComboButton
    dijit/form/templates/ComboButton.html
    dijit/form/ToggleButton
    dijit/form/_ToggleButtonMixin

widgets/widgets:
    widgets/widgets
    VectorGauge/widget/VectorGauge
    VectorGauge/lib/jquery-1.11.2
    VectorGauge/lib/snap.svg
    VectorGauge/widget/template/VectorGauge.html

dojo/dojo:
    dojo/dojo
    dojo/main
    dojo/_base/kernel
    dojo/has
    dojo/_base/config
    dojo/sniff
    dojo/_base/lang
    dojo/_base/array
    dojo/ready
    dojo/domReady
    dojo/_base/declare
    dojo/_base/connect
    dojo/on
    dojo/topic
    dojo/Evented
    dojo/aspect
    dojo/_base/event
    dojo/dom-geometry
    dojo/_base/window
    dojo/dom
    dojo/dom-style
    dojo/mouse
    dojo/_base/sniff
    dojo/keys
    dojo/_base/Deferred
    dojo/Deferred
    dojo/errors/CancelError
    dojo/errors/create
    dojo/promise/Promise
    dojo/promise/instrumentation
    dojo/promise/tracer
    dojo/when
    dojo/_base/json
    dojo/json
    dojo/_base/Color
    dojo/_base/browser
    dojo/_base/unload
    dojo/_base/html
    dojo/dom-attr
    dojo/dom-prop
    dojo/dom-construct
    dojo/dom-class
    dojo/_base/NodeList
    dojo/query
    dojo/selector/_loader
    dojo/NodeList-dom
    dojo/_base/xhr
    dojo/io-query
    dojo/dom-form
    dojo/request/watch
    dojo/request/util
    dojo/errors/RequestError
    dojo/errors/RequestTimeoutError
    dojo/request/xhr
    dojo/request/handlers
    dojo/_base/fx
    dojo/_base/loader

Process finished normally
    errors: 1
    warnings: 61
    build time: 3.97 seconds

**Comment by iamrob-nl** [comment]
I have created a new sandbox project and have received the same feedback...The strange thing is that the used library (Snap.SVG) is a single file which has 'eve' included.

More research is needed in finding the solution.

**Comment by iamrob-nl** [comment]
Hi @ghartwich, 

I have created a new version of the widget which no longer contains the Snap.js library. It works on my local environment.

I have not yet tested this on my sandbox environment, which doesn't seem to work properly for other reasons. Perhaps you might get the chance to test this earlier.
