### ISSUE TITLE
Could not create widget VectorGauge.widget.VectorGauge

### ISSUE THREAD

**Issue by ndv62** [iamrob-nl/VectorGauge#3]
Hello,

instead of loading the widget (tried both locally and on the Test-environment) this message appears:
'Could not create widget VectorGauge.widget.VectorGauge'

The data that should be displayed is correctly gathered by the microflow that I am using to fill the widget.

Any idea to what may be causing this problem?
I am using modeler version 7.16, and have tried on both the Chrome and Mozilla browsers.

Kind regards,

Nils

**Comment by iamrob-nl** [comment]
Hi Nils,

I have not yet tested the widget in the latest Mendix version. The way I have left it, the widget was working in that version. I will plan some time to check into this.

Best regards,

Rob

**Comment by iamrob-nl** [comment]
Just published a new release.

**Comment by ndv62** [comment]
Works like a charm, thanks!
